"""Added fields to include image url and image name

Revision ID: 22a93652a45f
Revises: 
Create Date: 2018-03-21 17:48:11.565978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a93652a45f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_url')
    op.drop_column('posts', 'image_filename')
    # ### end Alembic commands ###
